#!/usr/bin/env bash

set -e

mr() {
  local remote_url
  remote_url=$(git remote get-url origin)

  if [[ $remote_url = gitlab* ]]; then
    remote_url=${remote_url/://}
    remote_url=${remote_url/gitlab@/https://}
  fi

  local cmd

  case "$OSTYPE" in
    darwin*)
      cmd=open
      ;;
    cygwin)
      cmd=cygstart
      ;;
    *)
      # just assume we're on Linux
      cmd=xdg-open
  esac

  "$cmd" "${remote_url%.git}/merge_requests/new?merge_request[source_branch]=$(git symbolic-ref -q --short HEAD)&merge_request[force_remove_source_branch]=true"
}

mr
