#!/usr/bin/env bash

set -e

mr() {
  local remote_url
  remote_url=$(git remote get-url origin)

  if [[ $remote_url = git* ]]; then
    remote_url=${remote_url/://}
    remote_url=${remote_url/git*@/https://}
  fi

  remote_url=${remote_url%.git}

  git web--browse "${remote_url}/merge_requests/new?merge_request[source_branch]=$(git symbolic-ref -q --short HEAD)&merge_request[force_remove_source_branch]=true"
}

mr
