#!/usr/bin/env bash

set -e

mr() {
  local url
  url=$(git remote get-url origin)
	local cmd

  case "$OSTYPE" in
    darwin*) 
      cmd=open
			;;
    cygwin)
      cmd=cygstart
    *)
		  # just assume we're on Linux
		  cmd=xdg-open
  esac

  "$cmd" "${url%.git}/merge_requests/new?merge_request[source_branch]=$(git symbolic-ref -q --short HEAD)"
}

mr
